export const ConsoleList: Record<string, string> = {
  stm: "Steam",
  psx: "Playstation",
  ps2: "Playstation 2",
  ps3: "Playstation 3",
  ps4: "Playstation 4",
  ps5: "Playstation 5",
  nes: "Nintendo Entertainment System",
  sns: "Super Nintendo Entertainment System",
  n64: "Nintendo 64",
  gcb: "GameCube",
  gby: "Game Boy",
  gbc: "Game Boy Color",
  gba: "Game Boy Advance",
  nds: "Nintendo DS",
  wii: "WII",
  msm: "Master System",
  gmd: "Genesis / Mega Drive",
  drc: "Dreamcast",
};
